version: "3.9"
services:
  db:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: mssql-server
    environment:
      - ACCEPT_EULA=Y
      - MYSQL_PID=Developer
      - SA_PASSWORD=admin123!
      - MSSQL_TCP_PORT=1433
    ports:
      - 1433:1433