version: "3.7"

services:
  grafana:
    image: grafana/grafana-enterprise:latest
    ports:
      - 3001:3000
    networks:
      - monitoring
    user: "104"
    links:
      - prometheus
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config:/prometheus
    command:
      - "--config.file=/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
