name: .NET

on:
  push:
    paths:
    - backend/**.cs
    - backend/**.csproj
    - backend/**.json
    branches:
    - master
  pull_request:
    paths:
    - backend/**.cs
    - backend/**.csproj
    - backend/**.json

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    
    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: eu-central-1
        role-session-name: url-shortener_GithubAction
        role-to-assume: arn:aws:iam::418300535646:role/GithubActions

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Install dotnet-stryker tool
      run: dotnet tool install dotnet-stryker

    - name: Stryker
      working-directory: backend/UrlShortener.UnitTests
      run: dotnet stryker -r "progress" -r "cleartext" -r "html"

    - uses: actions/upload-artifact@v3
      with:
        name: Stryker result
        path: backend/UrlShortener.UnitTests/StrykerOutput/**/reports/mutation-report.html
