name: .NET

on:
  push:
    paths:
    - src/**.cs
    - src/**.csproj
    - src/**.json
  pull_request:
    paths:
    - src/**.cs
    - src/**.csproj
    - src/**.json

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Install dotnet-stryker tool
      run: dotnet tool install -g dotnet-stryker

    - name: Stryker
      working-directory: src/UrlShortener.UnitTests
      run: dotnet stryker -r "progress" -r "cleartext" -r "html"

    - uses: actions/upload-artifact@v3
      with:
        name: Stryker result
        path: src/UrlShortener.UnitTests/StrykerOutput/**/reports/mutation-report.html